<?php
/** @var  $this \app\core\View*/
$this->title = 'Home'; ?>
<section class="intro">
    <!-- content -->
    <div class="content">
        <!-- top -->
        <div class="top">
            <p>Join us for access to our artists music</p>
        </div>
        <!-- center -->
        <div class="login">
            <a class="button" href="signup" target="_blank"> Sign up</a>
        </div>
    </div>
</section>
