<?php

/** @var  $model \app\models\User */
/** @var   $this \app\core\View*/
$this->title = 'Login'; ?>

<?php $form = \app\core\form\Form::begin('', "post" ,'') ?>

<?php echo $form->field($model, 'Email', 'Email', 'Email') ?>
<?php echo $form->field($model, 'Password', 'Password', 'Password')->passwordField() ?>

<div class="signup">
    <button class="button" type="submit">Let's party</button>
</div>
<?php \app\core\form\Form::end() ?>
