<?php

/** @var  $this \app\core\View */
$this->title = 'artist id';
?>


<section class="block size_c" >

        <div class="feature artist">
            <!-- media -->
            <div class="media"> <img  src="./assets/img/artist/gamz2.png" alt=" artist photo"> </div>

            <!-- content -->
            <div class="content">

                <!-- center -->
                <div class="center">

                    <!-- line 1 -->
                    <h2></h2>


                </div>

            </div>
        </div>
        </section>


        <!-- description -->
        <div class="description">
            <p></p>
        </div>

        <!-- control -->
        <div class="control">

            <a class="button" href="" target="_blank"> Website</a>
            <a class="button" href="https://facebook.com/gamz233" target="_blank">Facebook</a>
            <a class="button" href="https://soundcloud.com/gamz233" target="_blank">Soundcloud</a>
            <a class="button" href="" target="_blank">Resident Advisor</a>
        </div>

