<?php
use app\core\Application;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css2?family=Overpass&display=swap" rel="stylesheet" />
    <link rel="shortcut icon" href="assets/gfx/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="assets/gfx/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="assets/css/normalize.css" />
    <link rel="stylesheet" href="assets/css/style.css" />

    <title><?= $this->title ?></title>
</head>

<body>
<header>
    <!-- logo -->
    <div class="logo-container">
        <a class="logo" href="./">
            <img src="assets/gfx/GROOVE_logo.svg" alt="logo" />
        </a>
    </div>

    <!--toggle-->
    <div class="burguer">
        <img src="assets/gfx/toggle.svg" alt="toggle" />
    </div>

    <!-- nav -->
    <nav>
        <ul id="header-nav" class="nav-links">
            <li class="nav-link">
                <!-- home -->
                <a href="./">Home</a>
            </li>

            <li class="nav-link">
                <!-- artist -->
                <a href="./artists">Artists</a>
            </li>

            <li class="nav-link">
                <!-- music -->
                <a href="releases">Releases</a>
            </li>

            <li class="nav-link">
                <!-- login -->
                <a href="signup">Sign Up</a>
            </li>
        </ul>
    </nav>
</header>

<!-- main -->
<main>
    <div class="alert"><?= Application::$app->session->getFlash('success')?></div>

    <section class="block size_d">
        <div class="inscription">
            {{content}}
            <div>
                <a class="question" href="signup">
                    <p>Don't have an account yet?</p>
                    <p>Sign up</p>
                </a>
            </div>
        </div>
    </section>
</main>

<!-- footer -->
<footer>
    <nav>
        <ul class="nav-links">
            <li class="nav-link">
                <!-- home -->
                <a href="./">Home</a>
            </li>

            <li class="nav-link">
                <!-- artist -->
                <a href="artists">Artists</a>
            </li>

            <li class="nav-link">
                <!-- music -->
                <a href="music">Releases</a>
            </li>

            <li class="nav-link">
                <!-- login -->
                <a href="signup">Sign Up</a>
            </li>
        </ul>
    </nav>
</footer>

<!-- script -->
<script src="assets/js/script.js"></script>
</body>
</html>
