<?php

/** @var $user\app\models\user */

$this->title = 'Edit User';

?>


<section class="c">

    <h1>Edit User</h1>
    <form method="post">
        <div>
            <label for="firstname">First name</label>
            <input type="text" id="firstname" name="Firstname" value="<?=$user['Firstname']?>">
        </div>
        <div>
            <label for="lastname">Last name</label>
            <input type="text" id="lastname" name="Lastname" value="<?= $user['Lastname']?>">

            <div>
                <label for="nickname">Nick name</label>
                <input type="text" id="nickname" name="Nickname" value="<?= $user['Nickname']?>">
            </div>
        </div>
        <div>
            <label for="email">Email</label>
            <input type="email" id="email" name="Email" value="<?= $user['Email']?>">
        </div>
        <div class="field">
            <label for="admin"> Role

                <select  id="admin" name="Admin">
                    <option value="<?= $user['Admin']?>" selected>  <?php
                        if (intval($user['Admin']) ==1):
                            echo 'Visitor';
                        elseif (intval($user['Admin']) ==2):
                            echo 'Artist';
                        elseif (intval($user['Admin']) ==3):
                            echo 'Admin';
                        endif;
                        ?></option>
                    <option type="number" id="admin" name="Admin" value="1">Visitor</option>
                    <option id="admin" name="Admin" value="2">Artist</option>
                    <option  id="admin" name="Admin" value="3">Admin</option>
                </select>
            </label>
        </div>

        <input type="hidden" value="<?=$user['Id'];?>" name="id">

        <button type="submit">Update</button>

    </form>

</section>

