<?php

/** @var $user \app\models\User */
/** @var   $this \app\core\View*/

$this->title = 'User';

?>

<h1> Users List</h1>
<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Nick Name</th>
            <th>Email</th>
            <th>Admin</th>
            <th class="text-right">Actions</th>
        </tr>
        </thead>
        <tbody>


        <?php foreach($user['user'] as $item): ?>



            <tr>

                <td><?=htmlspecialchars($item['Firstname']); ?></td>
                <td>['LastName']</td>
                <td>[NickName]</td>
                <td>['Email']</td>
                <td>['Admin'] </td>
                <td class="text-right">
                    <a <!--class="btn btn-sm btn-outline-secondary" href="index.php?controller=Admin\&task=update&id="><i class="fa fa-pencil"></i> -->Change</a>
                </td>
            </tr>
        <?php endforeach; ?>


        </tbody>
    </table>
</div>