<?php

/** @var $model \app\models\Events */
$this->title = 'Add Event'; ?>
<div class="artist_main">
    <aside>
    <div class="asideburguer">
        <img src="assets/gfx/toggle.svg" alt="toggle" />
    </div>
        <!-- nav -->
        <nav>

            <ul id="aside-nav" class="aside-links">

                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_profile?id=<?=$artist['a_Id']?>">Artist profile</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <!-- home -->

                        <a href="create_artist">Create Artist</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_albums">Albums</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_events">Events</a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </nav>
</aside>
    <section class="artist_content">
        <div class="admin_view">
            <h2>Add Event</h2>
            <?php $form = \app\core\form\Form::begin('', "post" , "multipart/form-data") ?>
            <?= $form->field($model, 'Name', 'Name', 'Name') ?>
            <?= $form->field($model, 'Url', 'Url' , 'Url'  ) ?>
            <?= $form->field($model, 'Location', 'Location', 'Location' ) ?>
            <?= $form->field($model, 'Date', 'Date', 'Date' ) ->date() ?>
            <?= $form->field($model, 'Time', 'Time' , 'Time'  ) ->time()?>


            <div class="signup">
                <button class="button" type="submit">Save</button>
            </div>
            <?php \app\core\form\Form::end() ?>
        </div>
    </section>
</div>

