<?php
/** @var $artist\app\controllers\ArtistController */
/** @var   $this \app\core\View */
$this->title = 'Backstage'; use app\core\Application; ?>
<div class="artist_main">
       <aside>
    <div class="asideburguer">
        <img src="assets/gfx/toggle.svg" alt="toggle" />
    </div>
        <!-- nav -->
        <nav>

            <ul id="aside-nav" class="aside-links">

                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_profile?id=<?=$artist['a_Id']?>">Artist profile</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <!-- home -->

                        <a href="create_artist">Create Artist</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_albums">Albums</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_events">Events</a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </nav>
</aside>
    <section class="artist_content">
        <div class="admin_view">
            <h2>Welcome to the backstage</h2>
            <p>Here, you are able to create and manage your artist page content</p>
            <p>Have fun!</p>
        </div>
    </section>
</div>
