<?php
/** @var $model \app\models\Artist */
/** @var   $this \app\core\View */

$this->title = 'Artist profile'; ?>
<div class="artist_main">
       <aside>
    <div class="asideburguer">
        <img src="assets/gfx/toggle.svg" alt="toggle" />
    </div>
        <!-- nav -->
        <nav>

            <ul id="aside-nav" class="aside-links">

                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_profile?id=<?=$artist['a_Id']?>">Artist profile</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <!-- home -->

                        <a href="create_artist">Create Artist</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_albums">Albums</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_events">Events</a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </nav>
</aside>
    <section class="artist_content">
        <div class="admin_view">
            <h2>Create Artist Page</h2>

            <?php $form = \app\core\form\Form::begin('', "post","") ?>
            <?= $form->field($model, 'Name', 'Name', 'Name') ?>
            <?= $form->textArea($model, 'Description', 'Description', 'Description')?>

            <div class="signup">
                <button class="button" type="submit">Publish Artist</button>
            </div>
            <?php \app\core\form\Form::end() ?>
        </div>
    </section>
</div>
