<?php
/** @var $event \app\controllers\ArtistController */
/** @var $artist\app\controllers\ArtistController */


$this->title = 'Edit Event'; ?>
<div class="artist_main">
        <aside>
    <div class="asideburguer">
        <img src="assets/gfx/toggle.svg" alt="toggle" />
    </div>
        <!-- nav -->
        <nav>

            <ul id="aside-nav" class="aside-links">

                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_profile?id=<?=$artist['a_Id']?>">Artist profile</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <!-- home -->

                        <a href="create_artist">Create Artist</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_albums">Albums</a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if (!empty($artist['a_Id'])){
                    ?>
                    <li class="aside-link">
                        <a href="artist_events">Events</a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </nav>
</aside>
    <section class="artist_content">
        <div class="admin_view">
            <h2>Edit Event</h2>

            <form method="post">
                <div>
                    <label for="Name">Name</label>
                    <input type="text" id="Name" name="eve_Name" value="<?=$event['eve_Name']?>" />
                </div>
                <div>
                    <label for="Url">Link</label>
                    <input type="text" id="Url" name="eve_Url" value="<?=$event['eve_Url']?>" />
                </div>
                <div>
                    <label for="Location">Location</label>
                    <input type="text" id="Location" name="Location" value="<?=$event['Location']?>" />
                </div>
                <div>
                    <label for="Date">Date</label>
                    <input type="date" id="Date" name="eve_Date" value="<?=$event['eve_Date']?>" />
                </div>
                <div>
                    <label for="Time">Time</label>
                    <input type="Time" id="Time" name="eve_Time" value="<?=$event['eve_Time']?>" />
                </div>

                <input type="hidden" value="<?=$event['eve_Id']?>" name="id" />
                <button class="button" name="submit" type="submit">Update</button>
            </form>
        </div>
    </section>
</div>

