<?php

/** @var  $artists \app\controllers\AdminController */
/** @var   $this \app\core\View */

use app\core\Application;

$this->title = 'Artists List'; ?>
<section class="admin_content">
    <h2>Artists</h2>
    <div class="alert"><?= Application::$app->session->getFlash('success')?></div>
    <div>
        <table class="table">
            <thead>
            <tr>
                <th>User Name</th>
                <th>Artist Name</th>
                <th>Email</th>
                <th>Page</th>
                <th>Del</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($artists as $item):?>

                <tr>
                    <td><?=$item['Firstname']?></td>
                    <td><?=$item['Name'] ?></td>
                    <td><?=$item['Email'] ?></td>
                    <td>
                        <a href="artist_detail?id=<?=$item['Id']?>">
                            <i class="far fa-eye"></i>
                        </a>
                    </td>
                    <td>
                        <a href="delete_artist?id=<?=$item['Id']?>" class="delete" data-confirm="Are you sure to delete this Artist?"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

</section>
