<?php

/** @var $model \app\models\Admin */
/** @var   $this \app\core\View*/

$this->title = 'dashboard';

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Overpass&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/css/normalize.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <title><?php use app\core\Application;

        echo $this->title ?> </title>
</head>

<body>
<header>

    <!-- logo -->
    <div class="dashboardHeader">
            <h1 class="title"><a  href="dashboard">Dashboard</a></h1>
        <div><a href="/profile">Welcome - <?php echo Application::$app->user->getDisplayName() ?></a></div>


    </div>

    <!--toggle-->
    <div class="burguer">
        <img src="/assets/gfx/toggle.svg" alt="toggle">
    </div>

    <aside>
    <!-- nav -->
    <nav>

        <ul id="header-nav" class="nav-links">
            <li class="nav-link"><!-- home -->
                <a  href="usersList">Users List</a>
            </li>

            <li class="nav-link"><!-- home -->
                <a  href="artistsList">Artists List</a>
            </li>

            <li class="nav-link"><!-- home -->
                <a  href="/">Home page</a>
            </li>

            <?php if (Application::isGuest()): ?>
                <li class="nav-link"><!-- login -->
                    <a href="login">Login</a>
                </li>
            <?php else: ?>
                <li class="nav-link">
                    <a href="/logout">Logout </a>

                </li>
            <?php endif; ?>
        </ul>


    </nav>
        </aside>
</header>

<!-- main -->
<main>
{{content}}
</main>
<!-- footer -->
<footer>

    <nav>


    </nav>
</footer>
<!-- script -->
<script src="/assets/js/script.js"></script>


</body>

</html>