<?php

/** @var  $users \app\controllers\AdminController */
/** @var  $user \app\controllers\AdminController */
/** @var  $this \app\core\View*/


use app\core\Application;

$this->title = 'Users List'; ?>

<section class="admin_content">
    <h2>Users List</h2>
    <div class="alert"><?= Application::$app->session->getFlash('success')?></div>
    <div>
        <table class="table">
            <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Nick Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Edit</th>
                <th>Del</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($users as $item):?>

                <tr>
                    <td><?=($item['Firstname']); ?></td>
                    <td><?=($item['Lastname']); ?></td>
                    <td><?=($item['Nickname']); ?></td>
                    <td><?=($item['Email']); ?></td>
                    <td>
                        <?php
                        if (intval($item['Admin']) ==1):
                            echo 'Visitor';
                        elseif (intval($item['Admin']) ==2):
                            echo 'Artist';
                        elseif (intval($item['Admin']) ==3):
                            echo 'Admin';
                        endif;
                        ?>
                    </td>
                    <td>
                        <a href="edit_user?id=<?=$item['Id']?>"><i class="fas fa-pencil-alt"></i></a>
                    </td>
                    <td>
                        <a href="delete_user?id=<?=$item['Id']?>" class="delete" data-confirm="Are you sure to delete this User?" ><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

</section>
